-- Replace incomplete easy_bundle entries with full list (106 bundles, 3 pages)
-- and add Wiz checkout upsell data (3 entries).
-- Source: Easy Bundle Builder app screenshots 2026-06-22 (all 3 pages).
DELETE FROM campaigns.bundle_catalog WHERE bundle_app IN ('easy_bundle', 'wiz');

-- ── Easy Bundle Builder — Page 1 ─────────────────────────────────────────────
INSERT INTO campaigns.bundle_catalog (title, bundle_app, status) VALUES
  ('იყიდე მეტი - დაზოგე მეტი',                              'easy_bundle', 'active'),
  ('MEAMA Outlet',                                            'easy_bundle', 'active'),
  ('Multicapsule Machine + 5 Boxes - 399 Gel',               'easy_bundle', 'active'),
  ('Versatile + 5 Boxes 799₾',                               'easy_bundle', 'active'),
  ('Versatile + 2 box (12 capsules) + cup + holder',         'easy_bundle', 'active'),
  ('Multi + 1 Box + cup + holder',                           'easy_bundle', 'active'),
  ('vers+boxes',                                             'easy_bundle', 'active'),
  ('mult+boxes',                                             'easy_bundle', 'active'),
  ('winter-offer',                                           'easy_bundle', 'active'),
  ('OLD MIX',                                                'easy_bundle', 'active'),
  ('Cappuccino time',                                        'easy_bundle', 'active'),
  ('test',                                                   'easy_bundle', 'active'),
  ('Overstock_discount',                                     'easy_bundle', 'active'),
  ('multioffer20',                                           'easy_bundle', 'active'),
  ('Versatile + 12 Boxes 599₾',                             'easy_bundle', 'active'),
  ('Multicapsule Machine + 6 Boxes - 249 Gel',               'easy_bundle', 'active'),
  ('6 multi + metal cup 115',                                'easy_bundle', 'active'),
  ('7 espresso + metal cup 115',                             'easy_bundle', 'active'),
  ('Milk Frother + cups',                                    'easy_bundle', 'active'),
  ('espresso machine + 7 Box 349',                           'easy_bundle', 'active'),
  ('6 ukofeino - 89',                                        'easy_bundle', 'active'),
  ('kids-drinks',                                            'easy_bundle', 'active'),
  ('strong drinks',                                          'easy_bundle', 'active'),
  ('Winter Drinks offer',                                    'easy_bundle', 'active'),
  ('gamajansagebeli sasmelebi',                              'easy_bundle', 'active'),
  ('6 ფერის ნაკრები პატარა ჭიქა = 99 ლარი',                'easy_bundle', 'active'),
  ('6 ფერის ნაკრები დიდი ჭიქა = 119 ლარი',                 'easy_bundle', 'active'),
  ('0.5 კგ. მოხალული მარცვალი + 2 დიდი თეთრი ჭიქა = 49 ლ','easy_bundle', 'active'),
  ('1 კგ. მოხალული მარცვალი + 2 დიდი თეთრი ჭიქა = 89 ლ',  'easy_bundle', 'active'),
  ('5 თურქული ყავა + 2 გამჭ ჭიქა = 49 ლარი',               'easy_bundle', 'active'),
  ('ყავის პაკეტების 4 შეკვრა და მინის 2 ჭიქა - 49 ლარად',  'easy_bundle', 'active'),
  ('6 ნალექიანი ყავა და მეტალის ჭიქა - 39 ლარი',           'easy_bundle', 'active'),
  ('ყავის პაკეტების 3 შეკვრა და მეტალის ჭიქა - 39 ლარად',  'easy_bundle', 'active'),
  ('0.5კგ. მოხალული მარცვალი და მეტალის ჭიქა - 49 ლარად',  'easy_bundle', 'active'),
  ('1 კგ. მოხალული მარცვალი და მეტაილს ჭიქა - 89 ლ',       'easy_bundle', 'active'),
  ('5 ნებისმიერი კოლოფი და ჰოლდერი - 67 ლ',               'easy_bundle', 'active'),
  ('5 ნებისმიერი კოლოფი და არომატული სანთელი - 67 ლ',      'easy_bundle', 'active'),
  -- disabled
  ('3+ Boxes + Cup',                                         'easy_bundle', 'inactive'),
  ('3+ Boxes + Holder',                                      'easy_bundle', 'inactive'),
  ('6 Multicapsule Boxes - 99Gel',                           'easy_bundle', 'inactive'),
  ('7 Espresso Boxes - 99Gel',                               'easy_bundle', 'inactive'),
  ('Milk Frother + 5 Multicapsule Boxes - 149 Gel',         'easy_bundle', 'inactive'),
  ('Milk Frother + 2 Espresso Boxes',                        'easy_bundle', 'inactive'),
  ('Healthy Line & Metal Cup - 1',                           'easy_bundle', 'inactive'),
  ('espresso + 1 box + holder',                              'easy_bundle', 'inactive'),
  ('Winter-drinks',                                          'easy_bundle', 'inactive'),
  ('Overstock_dis_ver2',                                     'easy_bundle', 'inactive'),
  ('Multicapsule Offer',                                     'easy_bundle', 'inactive'),
  ('6 Multi - 89',                                           'easy_bundle', 'inactive'),
  ('7-espreso-89',                                           'easy_bundle', 'inactive');

-- ── Easy Bundle Builder — Page 2 ─────────────────────────────────────────────
INSERT INTO campaigns.bundle_catalog (title, bundle_app, status) VALUES
  ('ვერსეტაილი, 6 ნებისმიერი კოლოფი, მეტალის ჭიქა, ჰოლდერი, სანთელი - 499 ლარი', 'easy_bundle', 'active'),
  ('მულტიკაფსულის სასაჩუქრე ნაკრები - აპარატი, 6 კოლოფი, ჭიქა, ჰოლდერი, სანთელი - 299 ლარი', 'easy_bundle', 'active'),
  ('6 MultiCapsule Boxes - 72Gel',                           'easy_bundle', 'active'),
  ('7 Espresso Boxes - 70Gel',                               'easy_bundle', 'active'),
  ('6 MultiCapsule Boxes - 72Gel us machine capsules',       'easy_bundle', 'active'),
  ('6 Capsule Us',                                           'easy_bundle', 'active'),
  ('7 espreso box for 70 gel',                               'easy_bundle', 'active'),
  ('Machine US + 6 Capsules for 199',                        'easy_bundle', 'active'),
  ('ESPRESO MACHINE AND 7 BOXES FOR 226 gel',                'easy_bundle', 'active'),
  ('Machine + Cup 149 gel',                                  'easy_bundle', 'active'),
  ('Svezia + Cup 199 gel',                                   'easy_bundle', 'active'),
  ('Versatile + Holder',                                     'easy_bundle', 'active'),
  ('versatile + holder 329Gel',                              'easy_bundle', 'active'),
  ('Us Machine + Holder',                                    'easy_bundle', 'active'),
  ('Eu machine + holder 139Gel',                             'easy_bundle', 'active'),
  ('Svezia + holder 189',                                    'easy_bundle', 'active'),
  ('7 capsule box EU + metal Cup 92',                        'easy_bundle', 'active'),
  ('6 multicapsule boxes + 1 metal cup 99 gel',              'easy_bundle', 'active'),
  ('1kg 55gel',                                              'easy_bundle', 'active'),
  ('6 ნალექიანი + მეტალის ჭიქა',                            'easy_bundle', 'active'),
  ('ნალექიანი პაკეტები',                                    'easy_bundle', 'active'),
  ('essentials 3 cup holder 69.99',                          'easy_bundle', 'active'),
  ('მულტიაპარატის preorder',                                'easy_bundle', 'active'),
  ('კაფსულების ბოქსი',                                      'easy_bundle', 'active'),
  ('MEAMA',                                                  'easy_bundle', 'active'),
  ('ევროპული კაფსულები',                                    'easy_bundle', 'active'),
  ('7 EU cup1',                                              'easy_bundle', 'active'),
  ('6 AM 1cup',                                             'easy_bundle', 'active'),
  ('2 kids 1 cup = 48gel',                                   'easy_bundle', 'active'),
  ('2+1 მულტიკაფსულა',                                     'easy_bundle', 'active'),
  ('4 თურქულის პაკეტები + პატარა მეტალის ჭიქა = 34₾',     'easy_bundle', 'active'),
  ('holder + am capsules = 59₾',                            'easy_bundle', 'active'),
  ('holder + eu cap = 49₾',                                 'easy_bundle', 'active'),
  ('4eu + 5am = 99₾',                                       'easy_bundle', 'active'),
  ('versetile + set 349₾',                                  'easy_bundle', 'active'),
  ('multimachine + 2 box = 119₾',                           'easy_bundle', 'active'),
  ('5 multi + 2 metal cup=99gel',                            'easy_bundle', 'active'),
  ('5euro + 2 metal cup=89gel',                              'easy_bundle', 'active'),
  ('versatile + 2 multi =349₾',                             'easy_bundle', 'active'),
  ('versatile + 2 multi = 349₾',                            'easy_bundle', 'active'),
  ('capuchinator + metal cup 85 gel',                        'easy_bundle', 'active'),
  ('versatile + milk frother = 399lari',                     'easy_bundle', 'active'),
  ('veratile + 5 capsule =450gel (EB)',                      'easy_bundle', 'active'),
  ('5 capsule + 1 cup (EB)',                                 'easy_bundle', 'active'),
  ('3+1 (Full Page A)',                                      'easy_bundle', 'active'),
  ('3+1 (Landing Page)',                                     'easy_bundle', 'active'),
  ('3+1 (Full Page B)',                                      'easy_bundle', 'active'),
  ('all-versatile+5scapsule-202606 (EB)',                    'easy_bundle', 'active'),
  -- disabled
  ('საბავშვო სასმელები',                                    'easy_bundle', 'inactive'),
  ('can + 2cup 39₾',                                        'easy_bundle', 'inactive');

-- ── Easy Bundle Builder — Page 3 ─────────────────────────────────────────────
INSERT INTO campaigns.bundle_catalog (title, bundle_app, status) VALUES
  ('ვერსიტაილი 2 ევროპული კაფ. 2ამერიკული კაფ.',            'easy_bundle', 'active'),
  ('bundle',                                                  'easy_bundle', 'active'),
  ('Starter Kit Versatile',                                  'easy_bundle', 'active'),
  ('Multicapsule starter kit (EB)',                          'easy_bundle', 'active'),
  ('1kg 2+1',                                               'easy_bundle', 'active'),
  ('შეიძინე მეტი დაზოგე მეტი (Landing Page)',               'easy_bundle', 'active');

-- ── Wiz: Checkout Upsell ─────────────────────────────────────────────────────
INSERT INTO campaigns.bundle_catalog (title, bundle_app, status) VALUES
  ('ჭიქები - ჩექაუთი vol2',     'wiz', 'active'),
  ('Thank you page: Cups Offer', 'wiz', 'inactive'),
  ('ჭიქები - ჩექაუთი',          'wiz', 'inactive');
